const fs = require('fs');

const categories = {
    "Alimentation": [
        { title: "Manger 0g de viande rouge pendant 3 jours", points: 40 },
        { title: "Faire au moins 1 repas 100% végétarien aujourd'hui", points: 20 },
        { title: "Acheter 3 fruits/légumes de saison cette semaine", points: 20 },
        { title: "Manger local (produits < 100km) pour 1 repas", points: 40 },
        { title: "Cuisiner un repas avec les restes cette semaine", points: 10 },
        { title: "Faire 0 gaspillage de nourriture pendant 3 jours", points: 20 },
        { title: "Faire son propre pain 1 fois cette semaine", points: 50 },
        { title: "Faire 1 gâteau maison pour éviter l'industriel", points: 20 },
        { title: "Acheter au moins 3 produits en vrac cette semaine", points: 30 },
        { title: "Ne boire que de l'eau du robinet toute la journée", points: 10 },
        { title: "Éviter totalement les produits transformés aujourd'hui", points: 40 },
        { title: "Cuisiner 1 recette 100% végétalienne cette semaine", points: 40 },
        { title: "Préparer 2 fois sa lunchbox pour le travail", points: 30 },
        { title: "Composter 1 kilo de déchets organiques", points: 50 },
        { title: "Remplacer la viande par des protéines végétales 1 fois", points: 20 },
        { title: "Cuisiner 1 nouvelle légumineuse (lentilles, pois...)", points: 20 },
        { title: "Faire ses courses au marché local cette semaine", points: 40 },
        { title: "N'acheter aucune bouteille en plastique de la semaine", points: 20 },
        { title: "Remplacer 1 dessert lacté par 1 fruit", points: 10 },
        { title: "Cuisiner 1 litre de son propre lait végétal", points: 50 },
        { title: "Remplacer 1 encas par des graines ou des noix", points: 10 },
        { title: "Refuser 1 emballage alimentaire au supermarché", points: 20 },
        { title: "Boire ses cafés sans gobelet jetable aujourd'hui", points: 10 },
        { title: "Consommer 1 produit imparfait acheté avec remise anti-gaspi", points: 10 },
        { title: "Cuisiner 1 soupe anti-gaspi avec des légumes flétris", points: 30 },
        { title: "Faire 1 repas au tofu ou au seitan cette semaine", points: 20 },
        { title: "Préparer ses menus pour les 3 prochains jours", points: 30 },
        { title: "Congeler 2 restes alimentaires avant qu'ils ne périssent", points: 20 },
        { title: "Acheter au moins 1 produit certifié bio cette semaine", points: 20 },
        { title: "Remplacer 1 portion de fromage par une alternative végétale", points: 30 }
    ],
    "Transport": [
        { title: "Utiliser 100% les transports en commun aujourd'hui", points: 20 },
        { title: "Aller 1 fois au travail/école à vélo cette semaine", points: 40 },
        { title: "Faire 1 trajet de moins de 3km à pied plutôt qu'en voiture", points: 30 },
        { title: "Réaliser 1 trajet en covoiturage cette semaine", points: 40 },
        { title: "Faire 1 journée de télétravail pour éviter 1 trajet", points: 50 },
        { title: "Prendre 1 fois le train au lieu de la voiture", points: 50 },
        { title: "Acheter un billet de train pour le prochain trajet long (>200km)", points: 40 },
        { title: "Prendre systématiquement les escaliers aujourd'hui", points: 10 },
        { title: "Regrouper 3 déplacements différents en 1 seule sortie", points: 20 },
        { title: "Faire 1 trajet de plus de 5km en transport doux", points: 40 },
        { title: "Vérifier et regonfler les pneus de 1 vélo", points: 20 },
        { title: "Conduire en éco-conduite (sans surrégimes) sur 1 trajet", points: 30 },
        { title: "Couper le moteur sur 3 arrêts d'affilée en voiture", points: 10 },
        { title: "Vérifier la pression de 4 pneus de voiture ce mois-ci", points: 20 },
        { title: "Faire 1 trajet en voiture de plus de 30min sans la clim", points: 20 },
        { title: "Réaliser l'entretien de son vélo (freins, nettoyage)", points: 20 },
        { title: "Proposer 1 trajet au covoiturage sur une application", points: 50 },
        { title: "Marcher au moins 5000 pas aujourd'hui", points: 30 },
        { title: "Faire 1 trajet de plus de 10km en métro/tram", points: 20 },
        { title: "Faire ses courses de la semaine entièrement à pied", points: 30 },
        { title: "Laisser la voiture au garage pendant 48h de suite", points: 40 },
        { title: "Ne prendre qu'un sac de moins de 10kg pour son prochain voyage", points: 20 },
        { title: "Organiser 1 trajet libre de plus de 2 personnes en covoiturage", points: 50 },
        { title: "Remplacer 1 déplacement professionnel par 1 visio", points: 10 },
        { title: "Optimiser 1 trajet GPS sans aucun détour inutile", points: 10 },
        { title: "Conduire 1 fois à 110 km/h max sur autoroute (>50km)", points: 30 },
        { title: "Passer 1 weekend complet de vacances sans prendre de vol", points: 50 },
        { title: "Faire 1 court trajet urbain en trottinette partagée/personnelle", points: 20 },
        { title: "Participer à 2 jours de covoiturage domicile-travail", points: 40 },
        { title: "Couper la clim 5 minutes avant d'arriver lors d'1 trajet", points: 10 }
    ],
    "Énergie": [
        { title: "Pendant 3 jours, éteindre 3 appareils habituellement en veille", points: 20 },
        { title: "Baisser le radiateur de 1°C pendant 24h", points: 40 },
        { title: "Éteindre la box internet toute la nuit pendant 3 jours", points: 10 },
        { title: "Prendre 1 douche chronométrée à moins de 5 minutes", points: 30 },
        { title: "Faire 1 lessive exclusivement à 30°C", points: 20 },
        { title: "Étendre 1 tournée de linge à l'air libre (sans sèche-linge)", points: 20 },
        { title: "Retirer le givre du congélateur cette semaine (1 dégivrage)", points: 50 },
        { title: "Toujours utiliser 1 couvercle pour bouillir de l'eau aujourd'hui", points: 10 },
        { title: "Rester dans la lumière naturelle 4h de suite sans éclairage", points: 10 },
        { title: "Remplacer 1 ampoule usagée ou vieillissante par 1 ampoule LED", points: 30 },
        { title: "Ne pas allumer la clim pendant la journée complète", points: 30 },
        { title: "Débrancher 1 multiprise complète pour la nuit", points: 10 },
        { title: "Charger son téléphone en mode avion à 100% au moins 1 fois", points: 10 },
        { title: "Supprimer 50 mails inutiles de sa boîte de réception", points: 20 },
        { title: "Garder la luminosité d'écran < 50% toute la journée", points: 10 },
        { title: "Fermer tous ses volets dès la nuit tombée pendant 3 jours", points: 20 },
        { title: "Couper la lumière systématiquement en quittant les pièces aujourd'hui", points: 10 },
        { title: "Lancer 1 cycle du lave-vaisselle uniquement en mode Eco", points: 20 },
        { title: "Garder 1 cycle de lave-vaisselle jusqu'à ce qu'il soit 100% plein", points: 20 },
        { title: "Vider et mieux réorganiser 1 étage complet de son frigo pour l'optimiser", points: 40 },
        { title: "Purger 2 radiateurs à domicile cette semaine", points: 50 },
        { title: "Regarder 3 vidéos sur une résolution max de 480p", points: 20 },
        { title: "Se désabonner manuellement de 5 newsletters publicitaires", points: 30 },
        { title: "Fermer 10 onglets inactifs restés ouverts depuis longtemps", points: 10 },
        { title: "Nettoyer 1 filtre d'aération (aspirateur, machine ou VMC) ce mois-ci", points: 40 },
        { title: "Attendre que le panier à linge soit 100% rempli avant 1 lavage", points: 20 },
        { title: "Débrancher 2 chargeurs solitaires toute la semaine", points: 10 },
        { title: "Se laisser sécher les cheveux à l'air libre plutôt qu'au sèche-cheveux 1 fois", points: 20 },
        { title: "Installer 1 mousseur économiseur d'eau sur un robinet de la maison", points: 40 },
        { title: "Faire 1 comparatif synthétique de ses 3 dernières factures électriques", points: 40 }
    ],
    "Consommation": [
        { title: "Acheter 0 plastique à usage unique (sac, portion...) sur 1 pleine semaine", points: 50 },
        { title: "Utiliser 1 gourde en remplacement d'1 bouteille plastique pendant 3 jours", points: 10 },
        { title: "Acheter 1 nouvelle pièce vestimentaire de seconde main plutôt que neuve", points: 40 },
        { title: "Refuser explicitement 3 tickets de caisse consécutifs", points: 10 },
        { title: "Donner 1 objet ou habit non utilisé depuis 1 an", points: 30 },
        { title: "Réparer 1 objet ou vêtement abîmé pour éviter le rachat", points: 50 },
        { title: "Fabriquer 1L de produit d'entretien écologique (ex: vinaigre blanc)", points: 50 },
        { title: "Faire toutes ses courses avec 2 grands sacs réutilisables au lieu de sacs jetables", points: 10 },
        { title: "Refuser 1 flyer, goodies promotionnel ou échantillon gratuit en rue/magasin", points: 20 },
        { title: "Lire 1 livre de seconde main (bibliothèque ou occasion) ce mois-ci", points: 30 },
        { title: "Se laver 3 fois au cours de la semaine avec 1 savon solide naturel", points: 20 },
        { title: "Se laver les cheveux avec 1 shampoing solide en barre pour essayer", points: 20 },
        { title: "Remplacer son coton jetable en utilisant 1 carré démaquillant lavable pour 1 semaine", points: 20 },
        { title: "Appliquer la méthode Furoshiki sur 1 paquet cadeau en l'emballant de tissu", points: 40 },
        { title: "Bloquer 1 achat en ligne impulsif et patienter 3 jours avant décision finale", points: 50 },
        { title: "Emprunter 1 objet ou livre en bibliothèque ou ludothèque locale cette semaine", points: 30 },
        { title: "Louer ou emprunter 1 outil spécifique au lieu d'un achat direct en grande surface", points: 40 },
        { title: "Mettre 1 autocollant Stop-Pub visible sur sa boîte aux lettres aujourd'hui", points: 20 },
        { title: "Rapporter 1 déchet électronique volumineux au recyclage (point de collecte)", points: 30 },
        { title: "Trier minutieusement une poubelle d'emballages complet (carton/papier) de la semaine", points: 20 },
        { title: "Laver et réutiliser 1 bocal de confiture en verre pour du stockage alimentaire", points: 10 },
        { title: "Mettre 1 projet DIY (Do It Yourself) en œuvre pour fabriquer 1 rangement", points: 50 },
        { title: "Acheter un bien d'ameublement dans 1 dépôt-vente ou brocante locale ce mois-ci", points: 40 },
        { title: "Désencombrer ses appareils ou stockage Cloud de 500 Mo minimum de données inutiles", points: 30 },
        { title: "S'engager formellement à ce que le prochain achat d'appareil (>100€) sera reconditionné", points: 40 },
        { title: "Effectuer 1 échange de service ou 1 prêt de matériel gratuit avec un voisin", points: 30 },
        { title: "Utiliser 1 indicateur environnemental (Eco-score, étiquette énergie) pour guider son prochain achat au supermarché", points: 20 },
        { title: "Sélectionner la livraison lente ou groupée pour sa prochaine commande e-commerce", points: 20 },
        { title: "Résister à l'achat d'eau minérale embouteillée pendant 1 semaine grâce à un filtre à eau naturel", points: 30 },
        { title: "Trier 5 vêtements propres en fin de vie dans l'armoire et les apporter à une borne de récupération", points: 30 }
    ]
};

let idCount = 1;
const all = [];

for (const [cat, items] of Object.entries(categories)) {
    for (const item of items) {
        all.push({
            id: idCount++,
            title: item.title,
            points: item.points,
            category: cat
        });
    }
}

const fs = require('fs');
fs.mkdirSync('./src/data', { recursive: true });
fs.writeFileSync('./src/data/challenges.json', JSON.stringify(all, null, 2));
console.log('100 défis ont été générés dans src/data/challenges.json avec leurs points par difficulté.');
